-- Auto-generated from schema-map-postgres.yaml (map@sha1:FAEA49A5D5F8FAAD9F850D0F430ED451C5C1D707)
-- engine: postgres
-- table:  webauthn_credentials

CREATE TABLE IF NOT EXISTS webauthn_credentials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rp_id VARCHAR(255) NOT NULL,
  subject VARCHAR(128) NOT NULL,
  user_id BIGINT NULL,
  credential_id VARCHAR(255) NOT NULL,
  public_key TEXT NOT NULL,
  added_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  last_used_at TIMESTAMPTZ(6) NULL,
  sign_count BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT ux_webauthn_cred UNIQUE (rp_id, credential_id)
);
